### ISSUE TITLE
Line representing "Path" in client UI

### ISSUE THREAD

**Issue by Brinly-DaveS** [dCentralizedSystems/customer-support#16]
[dCent question about line between data points..docx](https://github.com/dCentralizedSystems/customer-support/files/3322110/dCent.question.about.line.between.data.points.docx)

Please see attached with questions about "path line" connecting displayed data points. 

I'm not sure how you handle displaying lines connecting sequential data points.

**Comment by georgechrysanthakopoulos** [comment]
Hi Dave, there is an interpolation bug, so instead of the heat map oriented along the path you took, it seems to be doing latitude axis interpolation only.

in theory, when you choose a wider "path width" the path heatmap gets wider in the direction of travel
but that is not what is happening.

over the weekend i went away from using a poly line, to using a heat map only, if the distance between GPS waypoint is below the "label interval" (see new slider)
i will look into this today.

**Comment by georgechrysanthakopoulos** [comment]
found and fixed the interpolation issue, lat was mixed with long. also, we now display the yellow line, but the thickness affects *only* the heat map. Affecting the thickness of the polyLine causes rendering artifacts. see attached, let me know what you think (notice i adjusted the label interval and path width for the image below)
![Screen Shot 2019-06-24 at 12 14 50 PM](https://user-images.githubusercontent.com/978440/60045499-e513cc80-9679-11e9-8538-553066b01836.png)

**Comment by georgechrysanthakopoulos** [comment]
improved interpolation further, so there are no gaps, even at fine map scale
![Screen Shot 2019-06-24 at 2 06 35 PM](https://user-images.githubusercontent.com/978440/60052122-5dce5500-9689-11e9-9b33-22671f87d561.png)
