### ISSUE TITLE
Can't Create New Plan in Cloud UI

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#42]
Perhaps I'm not thinking well yet early Saturday morning, but I cant see how to crate a new Plan in the Cloud UI (I can do this in the LCR UI).

**Comment by georgechrysanthakopoulos** [comment]
not yet supported. Plans currently need to originate on the robot, since, the user can use the robot to "locate" the initial waypoints / areas with the robot location as a sign post. we can implement this in the future and allow plan creation from either end. I will keep issue open to track but this is known limitation

**Comment by georgechrysanthakopoulos** [comment]
I was wrong. It is supported.
* unfreeze graph (pick any existing graph, like "default"
* click anywhere on map
* type in a new plan name in the dialog
* select "new" from selector for plan
* new 
![Screen Shot 2020-07-17 at 5 39 15 PM](https://user-images.githubusercontent.com/978440/87840497-c704a580-c854-11ea-86cf-e9e36d336568.png)
plan loads

On Robot:
Unfreeze plan, synchronize, refresh, new plan will show up in list of plans
![Screen Shot 2020-07-17 at 5 40 44 PM](https://user-images.githubusercontent.com/978440/87840494-c4a24b80-c854-11ea-9caf-63ef81e60fb3.png)

we can open different issues on usability of all this, if necessery
